services:
  db:

    # imagen de mysql
    image: mysql:8.4


    container_name: mysql_prod
    restart: always


    # forzar estandar moderno de charset
    # acceso para clientes legacy
    # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      # persistencia de datos
      - ./mysql_data:/var/lib/mysql

    ports:
      # PARA ACCESO REMOTO
      # COMENTAR SI SOLO SE ACCEDE DESDE EL BACKEND EN LA MISMA RED
      # Formate: "PUERTO_HOST:PUERTO_CONTAINER"
      - "3306:3306"

    networks:
      - backend_network

    # verifica cada 5s si la bd responde
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
networks:
  backend_network:
    driver: bridge
